packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - argon2

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - '@scarf/scarf'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

overrides:
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  nodemailer@<7.0.11: '>=7.0.11'
  nodemailer@<7.0.7: '>=7.0.7'
  nodemailer@<=7.0.10: '>=7.0.11'
  '@nestjs-modules/mailer>mjml': '^5.0.0-alpha.4'
