//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "blog_posts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub slug: String,
    pub title: String,
    #[sea_orm(column_name = "contentKey", column_type = "Text")]
    pub content_key: String,
    #[sea_orm(column_name = "contentSize")]
    pub content_size: Option<i32>,
    pub excerpt: Option<String>,
    #[sea_orm(column_name = "coverImage", column_type = "Text", nullable)]
    pub cover_image: Option<String>,
    #[sea_orm(column_name = "authorId", column_type = "Text")]
    pub author_id: String,
    #[sea_orm(column_name = "isPublished")]
    pub is_published: bool,
    #[sea_orm(column_name = "publishedAt")]
    pub published_at: Option<DateTime>,
    #[sea_orm(column_name = "viewCount")]
    pub view_count: i32,
    #[sea_orm(column_name = "metaTitle")]
    pub meta_title: Option<String>,
    #[sea_orm(column_name = "metaDescription")]
    pub meta_description: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::blog_comments::Entity")]
    BlogComments,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::AuthorId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Users,
}

impl Related<super::blog_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogComments.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
