//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::ProductSize;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "cart_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "cartId",
        column_type = "Text",
        unique_key = "cart_items_cartId_productId_size_key"
    )]
    pub cart_id: String,
    pub quantity: i32,
    #[sea_orm(
        column_name = "productId",
        column_type = "Text",
        unique_key = "cart_items_cartId_productId_size_key"
    )]
    pub product_id: String,
    #[sea_orm(unique_key = "cart_items_cartId_productId_size_key")]
    pub size: Option<ProductSize>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::carts::Entity",
        from = "Column::CartId",
        to = "super::carts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Carts,
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Products,
}

impl Related<super::carts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Carts.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
