//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::EventType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_name = "startDate")]
    pub start_date: DateTimeWithTimeZone,
    #[sea_orm(column_name = "endDate")]
    pub end_date: DateTimeWithTimeZone,
    pub location: Option<String>,
    pub r#type: EventType,
    pub organizer: Option<String>,
    pub attendees: Option<i32>,
    #[sea_orm(column_name = "surveyLink", column_type = "Text", nullable)]
    pub survey_link: Option<String>,
    #[sea_orm(column_name = "createdBy", column_type = "Text", nullable)]
    pub created_by: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
