//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::OAuthProvider;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "external_accounts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(unique_key = "external_accounts_provider_userId_key")]
    pub provider: OAuthProvider,
    #[sea_orm(
        column_name = "providerId",
        unique_key = "external_accounts_provider_providerId_key"
    )]
    pub provider_id: String,
    #[sea_orm(column_name = "providerEmail")]
    pub provider_email: Option<String>,
    #[sea_orm(column_name = "accessToken", column_type = "Text", nullable)]
    pub access_token: Option<String>,
    #[sea_orm(column_name = "refreshToken", column_type = "Text", nullable)]
    pub refresh_token: Option<String>,
    #[sea_orm(column_name = "expiresAt")]
    pub expires_at: Option<DateTime>,
    #[sea_orm(
        column_name = "userId",
        column_type = "Text",
        unique_key = "external_accounts_provider_userId_key"
    )]
    pub user_id: String,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
