//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
// ponytail: generated entities for full schema — allow until routes query each table
#![allow(dead_code, unused_imports)]

pub mod prelude;

pub mod addresses;
pub mod blog_comments;
pub mod blog_posts;
pub mod blog_tags;
pub mod cart_items;
pub mod carts;
pub mod devices;
pub mod events;
pub mod external_accounts;
pub mod mfa_backup_codes;
pub mod mfa_methods;
pub mod order_items;
pub mod orders;
pub mod payment_transactions;
pub mod product_size_stocks;
pub mod products;
pub mod reviews;
pub mod sea_orm_active_enums;
pub mod security_logs;
pub mod sessions;
pub mod shipping_addresses;
pub mod users;
pub mod vouchers;
