//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::OrderStatus;
use super::sea_orm_active_enums::PaymentStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "orders")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub code: String,
    #[sea_orm(column_name = "userId", column_type = "Text")]
    pub user_id: String,
    pub status: OrderStatus,
    #[sea_orm(column_name = "paymentStatus")]
    pub payment_status: PaymentStatus,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_name = "totalAmount")]
    pub total_amount: Decimal,
    #[sea_orm(column_name = "shippingFee")]
    pub shipping_fee: Decimal,
    #[sea_orm(column_name = "discountValue")]
    pub discount_value: Decimal,
    #[sea_orm(column_name = "shippingAddressId", column_type = "Text", unique)]
    pub shipping_address_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::order_items::Entity")]
    OrderItems,
    #[sea_orm(has_one = "super::payment_transactions::Entity")]
    PaymentTransactions,
    #[sea_orm(
        belongs_to = "super::shipping_addresses::Entity",
        from = "Column::ShippingAddressId",
        to = "super::shipping_addresses::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ShippingAddresses,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::order_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderItems.def()
    }
}

impl Related<super::payment_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentTransactions.def()
    }
}

impl Related<super::shipping_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShippingAddresses.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
