//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::PaymentTransactionStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "payment_transactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "orderId", column_type = "Text", unique)]
    pub order_id: String,
    // ponytail: `transactionCode` is the PayOS external API field (payment link id), not the
    // domain `Payment` Avoid `transaction` — kept for wire parity with Prisma/payOS
    #[sea_orm(column_name = "transactionCode", column_type = "Text", unique)]
    pub transaction_code: String,
    pub amount: Decimal,
    pub status: PaymentTransactionStatus,
    #[sea_orm(column_name = "paymentUrl", column_type = "Text", nullable)]
    pub payment_url: Option<String>,
    #[sea_orm(column_name = "payosData", column_type = "JsonBinary", nullable)]
    pub payos_data: Option<Json>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::orders::Entity",
        from = "Column::OrderId",
        to = "super::orders::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Orders,
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
