//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::ProductSlug;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "products")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_name = "isPublished")]
    pub is_published: bool,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    pub badge: Option<String>,
    #[sea_orm(column_name = "hasSizes")]
    pub has_sizes: bool,
    #[sea_orm(column_name = "priceCurrent")]
    pub price_current: Decimal,
    #[sea_orm(column_name = "priceDiscount")]
    pub price_discount: Option<Decimal>,
    #[sea_orm(column_name = "priceOriginal")]
    pub price_original: Option<Decimal>,
    #[sea_orm(column_name = "ratingCount")]
    pub rating_count: i32,
    #[sea_orm(column_name = "ratingValue", column_type = "Decimal(Some((3, 2)))")]
    pub rating_value: Decimal,
    pub stock: i32,
    #[sea_orm(unique)]
    pub slug: ProductSlug,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cart_items::Entity")]
    CartItems,
    #[sea_orm(has_many = "super::order_items::Entity")]
    OrderItems,
    #[sea_orm(has_many = "super::product_size_stocks::Entity")]
    ProductSizeStocks,
    #[sea_orm(has_many = "super::reviews::Entity")]
    Reviews,
}

impl Related<super::cart_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CartItems.def()
    }
}

impl Related<super::order_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderItems.def()
    }
}

impl Related<super::product_size_stocks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductSizeStocks.def()
    }
}

impl Related<super::reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reviews.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
