//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "DeviceType")]
pub enum DeviceType {
    #[sea_orm(string_value = "DESKTOP")]
    Desktop,
    #[sea_orm(string_value = "MOBILE")]
    Mobile,
    #[sea_orm(string_value = "TABLET")]
    Tablet,
    #[sea_orm(string_value = "UNKNOWN")]
    Unknown,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "DiscountType")]
pub enum DiscountType {
    #[sea_orm(string_value = "PERCENTAGE")]
    Percentage,
    #[sea_orm(string_value = "FIXED_AMOUNT")]
    FixedAmount,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "EventType")]
pub enum EventType {
    #[sea_orm(string_value = "MEETING")]
    Meeting,
    #[sea_orm(string_value = "WORKSHOP")]
    Workshop,
    #[sea_orm(string_value = "SOCIAL")]
    Social,
    #[sea_orm(string_value = "COMPETITION")]
    Competition,
    #[sea_orm(string_value = "SURVEY")]
    Survey,
    #[sea_orm(string_value = "OTHER")]
    Other,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "MFAMethod")]
pub enum MfaMethod {
    #[sea_orm(string_value = "TOTP")]
    Totp,
    #[sea_orm(string_value = "SMS")]
    Sms,
    #[sea_orm(string_value = "EMAIL")]
    Email,
    #[sea_orm(string_value = "BACKUP_CODE")]
    BackupCode,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "OAuthProvider")]
pub enum OAuthProvider {
    #[sea_orm(string_value = "GOOGLE")]
    Google,
    #[sea_orm(string_value = "FACEBOOK")]
    Facebook,
    #[sea_orm(string_value = "GITHUB")]
    Github,
    #[sea_orm(string_value = "APPLE")]
    Apple,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "OrderStatus")]
pub enum OrderStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "CONFIRMED")]
    Confirmed,
    #[sea_orm(string_value = "PROCESSING")]
    Processing,
    #[sea_orm(string_value = "SHIPPING")]
    Shipping,
    #[sea_orm(string_value = "DELIVERED")]
    Delivered,
    #[sea_orm(string_value = "CANCELLED")]
    Cancelled,
    #[sea_orm(string_value = "RETURNED")]
    Returned,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "PaymentStatus")]
pub enum PaymentStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "PAID")]
    Paid,
    #[sea_orm(string_value = "FAILED")]
    Failed,
    #[sea_orm(string_value = "REFUNDED")]
    Refunded,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "PaymentTransactionStatus"
)]
pub enum PaymentTransactionStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "PAID")]
    Paid,
    #[sea_orm(string_value = "CANCELLED")]
    Cancelled,
    #[sea_orm(string_value = "EXPIRED")]
    Expired,
    #[sea_orm(string_value = "FAILED")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "ProductSize")]
pub enum ProductSize {
    #[sea_orm(string_value = "S")]
    S,
    #[sea_orm(string_value = "M")]
    M,
    #[sea_orm(string_value = "L")]
    L,
    #[sea_orm(string_value = "XL")]
    Xl,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "ProductSlug")]
pub enum ProductSlug {
    #[sea_orm(string_value = "AO_THUN")]
    AoThun,
    #[sea_orm(string_value = "PAD_CHUOT")]
    PadChuot,
    #[sea_orm(string_value = "DAY_DEO")]
    DayDeo,
    #[sea_orm(string_value = "MOC_KHOA")]
    MocKhoa,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "SessionStatus")]
pub enum SessionStatus {
    #[sea_orm(string_value = "ACTIVE")]
    Active,
    #[sea_orm(string_value = "EXPIRED")]
    Expired,
    #[sea_orm(string_value = "REVOKED")]
    Revoked,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "UserRole")]
pub enum UserRole {
    #[sea_orm(string_value = "ADMIN")]
    Admin,
    #[sea_orm(string_value = "CUSTOMER")]
    Customer,
}
