//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::UserRole;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub password: Option<String>,
    #[sea_orm(column_name = "fullName")]
    pub full_name: Option<String>,
    pub phone: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub avatar: Option<String>,
    pub role: UserRole,
    #[sea_orm(column_name = "mfaEnabled")]
    pub mfa_enabled: bool,
    #[sea_orm(column_name = "mfaSecret", column_type = "Text", nullable)]
    pub mfa_secret: Option<String>,
    #[sea_orm(column_name = "emailVerified")]
    pub email_verified: bool,
    #[sea_orm(column_name = "phoneVerified")]
    pub phone_verified: bool,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::addresses::Entity")]
    Addresses,
    #[sea_orm(has_many = "super::blog_comments::Entity")]
    BlogComments,
    #[sea_orm(has_many = "super::blog_posts::Entity")]
    BlogPosts,
    #[sea_orm(has_one = "super::carts::Entity")]
    Carts,
    #[sea_orm(has_many = "super::devices::Entity")]
    Devices,
    #[sea_orm(has_many = "super::external_accounts::Entity")]
    ExternalAccounts,
    #[sea_orm(has_many = "super::mfa_backup_codes::Entity")]
    MfaBackupCodes,
    #[sea_orm(has_many = "super::mfa_methods::Entity")]
    MfaMethods,
    #[sea_orm(has_many = "super::orders::Entity")]
    Orders,
    #[sea_orm(has_many = "super::reviews::Entity")]
    Reviews,
    #[sea_orm(has_many = "super::sessions::Entity")]
    Sessions,
}

impl Related<super::addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Addresses.def()
    }
}

impl Related<super::blog_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogComments.def()
    }
}

impl Related<super::blog_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogPosts.def()
    }
}

impl Related<super::carts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Carts.def()
    }
}

impl Related<super::devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Devices.def()
    }
}

impl Related<super::external_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExternalAccounts.def()
    }
}

impl Related<super::mfa_backup_codes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MfaBackupCodes.def()
    }
}

impl Related<super::mfa_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MfaMethods.def()
    }
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reviews.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
