//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::DiscountType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "vouchers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(unique)]
    pub code: String,
    pub r#type: DiscountType,
    #[sea_orm(column_name = "usageLimit")]
    pub usage_limit: i32,
    #[sea_orm(column_name = "usedCount")]
    pub used_count: i32,
    #[sea_orm(column_name = "startDate")]
    pub start_date: DateTime,
    #[sea_orm(column_name = "endDate")]
    pub end_date: DateTime,
    #[sea_orm(column_name = "isActive")]
    pub is_active: bool,
    pub value: Decimal,
    #[sea_orm(column_name = "minSpend")]
    pub min_spend: Option<Decimal>,
    #[sea_orm(column_name = "maxDiscount")]
    pub max_discount: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
