/// <reference types="node" />

// This file was generated by Prisma, and assumes you have installed the following:
// pnpm install --save-dev prisma dotenv
import 'dotenv/config';

import { join } from 'path';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: join(__dirname, 'prisma', 'schema'),
  migrations: {
    path: join(__dirname, 'prisma', 'migrations'),
    seed: 'bun prisma/product.seed.ts',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
